export const Countries = {
  Afghanistan: { code: 'AF', countryName: 'Afghanistan' },
  AlandIslands: { code: 'AX', countryName: 'Åland Islands' },
  Albania: { code: 'AL', countryName: 'Albania' },
  Algeria: { code: 'DZ', countryName: 'Algeria' },
  AmericanSamoa: { code: 'AS', countryName: 'American Samoa' },
  Andorra: { code: 'AD', countryName: 'Andorra' },
  Angola: { code: 'AO', countryName: 'Angola' },
  Anguilla: { code: 'AI', countryName: 'Anguilla' },
  Antarctica: { code: 'AQ', countryName: 'Antarctica' },
  AntiguaAndBarbuda: { code: 'AG', countryName: 'Antigua and Barbuda' },
  Argentina: { code: 'AR', countryName: 'Argentina' },
  Armenia: { code: 'AM', countryName: 'Armenia' },
  Aruba: { code: 'AW', countryName: 'Aruba' },
  Australia: { code: 'AU', countryName: 'Australia' },
  Austria: { code: 'AT', countryName: 'Austria' },
  Azerbaijan: { code: 'AZ', countryName: 'Azerbaijan' },
  Bahamas: { code: 'BS', countryName: 'Bahamas' },
  Bahrain: { code: 'BH', countryName: 'Bahrain' },
  Bangladesh: { code: 'BD', countryName: 'Bangladesh' },
  Barbados: { code: 'BB', countryName: 'Barbados' },
  Belarus: { code: 'BY', countryName: 'Belarus' },
  Belgium: { code: 'BE', countryName: 'Belgium' },
  Belize: { code: 'BZ', countryName: 'Belize' },
  Benin: { code: 'BJ', countryName: 'Benin' },
  Bermuda: { code: 'BM', countryName: 'Bermuda' },
  Bhutan: { code: 'BT', countryName: 'Bhutan' },
  Bolivia: { code: 'BO', countryName: ' Plurinational State of Bolivia' },
  BonaireSintEustatiusAndSaba: { code: 'BQ', countryName: 'Bonaire, Sint Eustatius and Saba' },
  BosniaAndHerzegovina: { code: 'BA', countryName: 'Bosnia and Herzegovina' },
  Botswana: { code: 'BW', countryName: 'Botswana' },
  BouvetIsland: { code: 'BV', countryName: 'Bouvet Island' },
  Brazil: { code: 'BR', countryName: 'Brazil' },
  BritishIndianOceanTerritory: { code: 'IO', countryName: 'British Indian Ocean Territory' },
  UnitedStatesMinorOutlyingIslands: {
    code: 'UM',
    countryName: 'United States Minor Outlying Islands',
  },
  VirginIslandsBritish: { code: 'VG', countryName: 'Virgin Islands (British)' },
  VirginIslandsUS: { code: 'VI', countryName: 'Virgin Islands (U.S.)' },
  BruneiDarussalam: { code: 'BN', countryName: 'Brunei Darussalam' },
  Bulgaria: { code: 'BG', countryName: 'Bulgaria' },
  BurkinaFaso: { code: 'BF', countryName: 'Burkina Faso' },
  Burundi: { code: 'BI', countryName: 'Burundi' },
  Cambodia: { code: 'KH', countryName: 'Cambodia' },
  Cameroon: { code: 'CM', countryName: 'Cameroon' },
  Canada: { code: 'CA', countryName: 'Canada' },
  CaboVerde: { code: 'CV', countryName: 'Cabo Verde' },
  CaymanIslands: { code: 'KY', countryName: 'Cayman Islands' },
  CentralAfricanRepublic: { code: 'CF', countryName: 'Central African Republic' },
  Chad: { code: 'TD', countryName: 'Chad' },
  Chile: { code: 'CL', countryName: 'Chile' },
  China: { code: 'CN', countryName: 'China' },
  ChristmasIsland: { code: 'CX', countryName: 'Christmas Island' },
  CocosKeelingIslands: { code: 'CC', countryName: 'Cocos (Keeling) Islands' },
  Colombia: { code: 'CO', countryName: 'Colombia' },
  Comoros: { code: 'KM', countryName: 'Comoros' },
  Congo: { code: 'CG', countryName: 'Congo' },
  CongoDemocraticRepublic: { code: 'CD', countryName: 'Democratic Republic of the Congo' },
  CookIslands: { code: 'CK', countryName: 'Cook Islands' },
  CostaRica: { code: 'CR', countryName: 'Costa Rica' },
  Croatia: { code: 'HR', countryName: 'Croatia' },
  Cuba: { code: 'CU', countryName: 'Cuba' },
  Curaçao: { code: 'CW', countryName: 'Curaçao' },
  Cyprus: { code: 'CY', countryName: 'Cyprus' },
  CzechRepublic: { code: 'CZ', countryName: 'Czech Republic' },
  Denmark: { code: 'DK', countryName: 'Denmark' },
  Djibouti: { code: 'DJ', countryName: 'Djibouti' },
  Dominica: { code: 'DM', countryName: 'Dominica' },
  DominicanRepublic: { code: 'DO', countryName: 'Dominican Republic' },
  Ecuador: { code: 'EC', countryName: 'Ecuador' },
  Egypt: { code: 'EG', countryName: 'Egypt' },
  ElSalvador: { code: 'SV', countryName: 'El Salvador' },
  EquatorialGuinea: { code: 'GQ', countryName: 'Equatorial Guinea' },
  Eritrea: { code: 'ER', countryName: 'Eritrea' },
  Estonia: { code: 'EE', countryName: 'Estonia' },
  Ethiopia: { code: 'ET', countryName: 'Ethiopia' },
  FalklandIslandsMalvinas: { code: 'FK', countryName: 'Falkland Islands (Malvinas)' },
  FaroeIslands: { code: 'FO', countryName: 'Faroe Islands' },
  Fiji: { code: 'FJ', countryName: 'Fiji' },
  Finland: { code: 'FI', countryName: 'Finland' },
  France: { code: 'FR', countryName: 'France' },
  FrenchGuiana: { code: 'GF', countryName: 'French Guiana' },
  FrenchPolynesia: { code: 'PF', countryName: 'French Polynesia' },
  FrenchSouthernTerritories: { code: 'TF', countryName: 'French Southern Territories' },
  Gabon: { code: 'GA', countryName: 'Gabon' },
  Gambia: { code: 'GM', countryName: 'Gambia' },
  Georgia: { code: 'GE', countryName: 'Georgia' },
  Germany: { code: 'DE', countryName: 'Germany' },
  Ghana: { code: 'GH', countryName: 'Ghana' },
  Gibraltar: { code: 'GI', countryName: 'Gibraltar' },
  Greece: { code: 'GR', countryName: 'Greece' },
  Greenland: { code: 'GL', countryName: 'Greenland' },
  Grenada: { code: 'GD', countryName: 'Grenada' },
  Guadeloupe: { code: 'GP', countryName: 'Guadeloupe' },
  Guam: { code: 'GU', countryName: 'Guam' },
  Guatemala: { code: 'GT', countryName: 'Guatemala' },
  Guernsey: { code: 'GG', countryName: 'Guernsey' },
  Guinea: { code: 'GN', countryName: 'Guinea' },
  GuineaBissau: { code: 'GW', countryName: 'Guinea-Bissau' },
  Guyana: { code: 'GY', countryName: 'Guyana' },
  Haiti: { code: 'HT', countryName: 'Haiti' },
  HeardIslandAndMcDonaldIslands: { code: 'HM', countryName: 'Heard Island and McDonald Islands' },
  HolySee: { code: 'VA', countryName: 'Holy See' },
  Honduras: { code: 'HN', countryName: 'Honduras' },
  HongKong: { code: 'HK', countryName: 'Hong Kong' },
  Hungary: { code: 'HU', countryName: 'Hungary' },
  Iceland: { code: 'IS', countryName: 'Iceland' },
  India: { code: 'IN', countryName: 'India' },
  Indonesia: { code: 'ID', countryName: 'Indonesia' },
  CoteDIvoire: { code: 'CI', countryName: "Côte d'Ivoire" },
  Iran: { code: 'IR', countryName: ' Islamic Republic of Iran' },
  Iraq: { code: 'IQ', countryName: 'Iraq' },
  Ireland: { code: 'IE', countryName: 'Ireland' },
  IsleOfMan: { code: 'IM', countryName: 'Isle of Man' },
  Israel: { code: 'IL', countryName: 'Israel' },
  Italy: { code: 'IT', countryName: 'Italy' },
  Jamaica: { code: 'JM', countryName: 'Jamaica' },
  Japan: { code: 'JP', countryName: 'Japan' },
  Jersey: { code: 'JE', countryName: 'Jersey' },
  Jordan: { code: 'JO', countryName: 'Jordan' },
  Kazakhstan: { code: 'KZ', countryName: 'Kazakhstan' },
  Kenya: { code: 'KE', countryName: 'Kenya' },
  Kiribati: { code: 'KI', countryName: 'Kiribati' },
  Kuwait: { code: 'KW', countryName: 'Kuwait' },
  Kyrgyzstan: { code: 'KG', countryName: 'Kyrgyzstan' },
  LaoPeoplesDemocraticRepublic: { code: 'LA', countryName: "Lao People's Democratic Republic" },
  Latvia: { code: 'LV', countryName: 'Latvia' },
  Lebanon: { code: 'LB', countryName: 'Lebanon' },
  Lesotho: { code: 'LS', countryName: 'Lesotho' },
  Liberia: { code: 'LR', countryName: 'Liberia' },
  Libya: { code: 'LY', countryName: 'Libya' },
  Liechtenstein: { code: 'LI', countryName: 'Liechtenstein' },
  Lithuania: { code: 'LT', countryName: 'Lithuania' },
  Luxembourg: { code: 'LU', countryName: 'Luxembourg' },
  Macao: { code: 'MO', countryName: 'Macao' },
  Macedonia: { code: 'MK', countryName: 'Macedonia' },
  Madagascar: { code: 'MG', countryName: 'Madagascar' },
  Malawi: { code: 'MW', countryName: 'Malawi' },
  Malaysia: { code: 'MY', countryName: 'Malaysia' },
  Maldives: { code: 'MV', countryName: 'Maldives' },
  Mali: { code: 'ML', countryName: 'Mali' },
  Malta: { code: 'MT', countryName: 'Malta' },
  MarshallIslands: { code: 'MH', countryName: 'Marshall Islands' },
  Martinique: { code: 'MQ', countryName: 'Martinique' },
  Mauritania: { code: 'MR', countryName: 'Mauritania' },
  Mauritius: { code: 'MU', countryName: 'Mauritius' },
  Mayotte: { code: 'YT', countryName: 'Mayotte' },
  Mexico: { code: 'MX', countryName: 'Mexico' },
  Micronesia: { code: 'FM', countryName: ' Federated States of Micronesia' },
  Moldova: { code: 'MD', countryName: 'Moldova' },
  Monaco: { code: 'MC', countryName: 'Monaco' },
  Mongolia: { code: 'MN', countryName: 'Mongolia' },
  Montenegro: { code: 'ME', countryName: 'Montenegro' },
  Montserrat: { code: 'MS', countryName: 'Montserrat' },
  Morocco: { code: 'MA', countryName: 'Morocco' },
  Mozambique: { code: 'MZ', countryName: 'Mozambique' },
  Myanmar: { code: 'MM', countryName: 'Myanmar' },
  Namibia: { code: 'NA', countryName: 'Namibia' },
  Nauru: { code: 'NR', countryName: 'Nauru' },
  Nepal: { code: 'NP', countryName: 'Nepal' },
  Netherlands: { code: 'NL', countryName: 'Netherlands' },
  NewCaledonia: { code: 'NC', countryName: 'New Caledonia' },
  NewZealand: { code: 'NZ', countryName: 'New Zealand' },
  Nicaragua: { code: 'NI', countryName: 'Nicaragua' },
  Niger: { code: 'NE', countryName: 'Niger' },
  Nigeria: { code: 'NG', countryName: 'Nigeria' },
  Niue: { code: 'NU', countryName: 'Niue' },
  NorfolkIsland: { code: 'NF', countryName: 'Norfolk Island' },
  KoreaDemocraticRepublic: { code: 'KP', countryName: "Democratic People's Republic of Korea" },
  NorthernMarianaIslands: { code: 'MP', countryName: 'Northern Mariana Islands' },
  Norway: { code: 'NO', countryName: 'Norway' },
  Oman: { code: 'OM', countryName: 'Oman' },
  Pakistan: { code: 'PK', countryName: 'Pakistan' },
  Palau: { code: 'PW', countryName: 'Palau' },
  Palestine: { code: 'PS', countryName: 'Palestine' },
  Panama: { code: 'PA', countryName: 'Panama' },
  PapuaNewGuinea: { code: 'PG', countryName: 'Papua New Guinea' },
  Paraguay: { code: 'PY', countryName: 'Paraguay' },
  Peru: { code: 'PE', countryName: 'Peru' },
  Philippines: { code: 'PH', countryName: 'Philippines' },
  Pitcairn: { code: 'PN', countryName: 'Pitcairn' },
  Poland: { code: 'PL', countryName: 'Poland' },
  Portugal: { code: 'PT', countryName: 'Portugal' },
  PuertoRico: { code: 'PR', countryName: 'Puerto Rico' },
  Qatar: { code: 'QA', countryName: 'Qatar' },
  Kosovo: { code: 'XK', countryName: 'Republic of Kosovo' },
  Reunion: { code: 'RE', countryName: 'Reunion' },
  Romania: { code: 'RO', countryName: 'Romania' },
  RussianFederation: { code: 'RU', countryName: 'Russian Federation' },
  Rwanda: { code: 'RW', countryName: 'Rwanda' },
  SaintBarthelemy: { code: 'BL', countryName: 'Saint Barthelemy' },
  SaintHelenaAscensionAndTristanDaCunha: {
    code: 'SH',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  SaintKittsAndNevis: { code: 'KN', countryName: 'Saint Kitts and Nevis' },
  SaintLucia: { code: 'LC', countryName: 'Saint Lucia' },
  SaintMartinFrenchPart: { code: 'MF', countryName: 'Saint Martin (French part)' },
  SaintPierreAndMiquelon: { code: 'PM', countryName: 'Saint Pierre and Miquelon' },
  SaintVincentAndTheGrenadines: { code: 'VC', countryName: 'Saint Vincent and the Grenadines' },
  Samoa: { code: 'WS', countryName: 'Samoa' },
  SanMarino: { code: 'SM', countryName: 'San Marino' },
  SaoTomeAndPrincipe: { code: 'ST', countryName: 'Sao Tome and Principe' },
  SaudiArabia: { code: 'SA', countryName: 'Saudi Arabia' },
  Senegal: { code: 'SN', countryName: 'Senegal' },
  Serbia: { code: 'RS', countryName: 'Serbia' },
  Seychelles: { code: 'SC', countryName: 'Seychelles' },
  SierraLeone: { code: 'SL', countryName: 'Sierra Leone' },
  Singapore: { code: 'SG', countryName: 'Singapore' },
  SintMaartenDutchpart: { code: 'SX', countryName: 'Sint Maarten (Dutch part)' },
  Slovakia: { code: 'SK', countryName: 'Slovakia' },
  Slovenia: { code: 'SI', countryName: 'Slovenia' },
  SolomonIslands: { code: 'SB', countryName: 'Solomon Islands' },
  Somalia: { code: 'SO', countryName: 'Somalia' },
  SouthAfrica: { code: 'ZA', countryName: 'South Africa' },
  SouthGeorgiaAndTheSouthSandwichIslands: {
    code: 'GS',
    countryName: 'South Georgia and the South Sandwich Islands',
  },
  KoreaRepublic: { code: 'KR', countryName: 'Korea Republic' },
  SouthSudan: { code: 'SS', countryName: 'South Sudan' },
  Spain: { code: 'ES', countryName: 'Spain' },
  SriLanka: { code: 'LK', countryName: 'Sri Lanka' },
  Sudan: { code: 'SD', countryName: 'Sudan' },
  Suriname: { code: 'SR', countryName: 'Suriname' },
  SvalbardandJanMayen: { code: 'SJ', countryName: 'Svalbard and Jan Mayen' },
  Swaziland: { code: 'SZ', countryName: 'Swaziland' },
  Sweden: { code: 'SE', countryName: 'Sweden' },
  Switzerland: { code: 'CH', countryName: 'Switzerland' },
  SyrianArabRepublic: { code: 'SY', countryName: 'Syrian Arab Republic' },
  Taiwan: { code: 'TW', countryName: 'Taiwan' },
  Tajikistan: { code: 'TJ', countryName: 'Tajikistan' },
  Tanzania: { code: 'TZ', countryName: 'Tanzania' },
  Thailand: { code: 'TH', countryName: 'Thailand' },
  TimorLeste: { code: 'TL', countryName: 'Timor-Leste' },
  Togo: { code: 'TG', countryName: 'Togo' },
  Tokelau: { code: 'TK', countryName: 'Tokelau' },
  Tonga: { code: 'TO', countryName: 'Tonga' },
  TrinidadAndTobago: { code: 'TT', countryName: 'Trinidad and Tobago' },
  Tunisia: { code: 'TN', countryName: 'Tunisia' },
  Turkey: { code: 'TR', countryName: 'Turkey' },
  Turkmenistan: { code: 'TM', countryName: 'Turkmenistan' },
  TurksandCaicosIslands: { code: 'TC', countryName: 'Turks and Caicos Islands' },
  Tuvalu: { code: 'TV', countryName: 'Tuvalu' },
  Uganda: { code: 'UG', countryName: 'Uganda' },
  Ukraine: { code: 'UA', countryName: 'Ukraine' },
  UnitedArabEmirates: { code: 'AE', countryName: 'United Arab Emirates' },
  UK: { code: 'GB', countryName: 'United Kingdom of Great Britain and Northern Ireland' },
  UnitedStatesOfAmerica: { code: 'US', countryName: 'United States of America' },
  Uruguay: { code: 'UY', countryName: 'Uruguay' },
  Uzbekistan: { code: 'UZ', countryName: 'Uzbekistan' },
  Vanuatu: { code: 'VU', countryName: 'Vanuatu' },
  Venezuela: { code: 'VE', countryName: 'Venezuela' },
  Vietnam: { code: 'VN', countryName: 'Vietnam' },
  WallisAndFutuna: { code: 'WF', countryName: 'Wallis and Futuna' },
  WesternSahara: { code: 'EH', countryName: 'Western Sahara' },
  Yemen: { code: 'YE', countryName: 'Yemen' },
  Zambia: { code: 'ZM', countryName: 'Zambia' },
  Zimbabwe: { code: 'ZW', countryName: 'Zimbabwe' },
};
